### ISSUE TITLE
Park 2020 reference?

### ISSUE THREAD

**Issue by wenegrat** [oceanhackweek/ohw20-proj-argo-mapping#24]
Thanks for some very useful code examples. @dhruvbalwada I see discussion of a Park 2020 paper, could you please provide the reference?

**Comment by dhruvbalwada** [comment]
Hey @wenegrat !! wondering what you are doing poking around these mapping packages? :)

I believe the Park 2020 is not published yet (I'll connect it here when it is), but the basic idea for the method is described in [Kuusela and Stein 2018](https://royalsocietypublishing.org/doi/full/10.1098/rspa.2018.0400). Was there something more specific that you were looking for?

**Comment by wenegrat** [comment]
Thanks @dhruvbalwada. What I can't pretend to be a large-scale oceanographer occasionally? :) Happy to chat about the project I'm working on if you are interested, just send me an email.

I'm just interested in the estimation of the mean state from sparse data. I'll check out the Kusela and Stein paper in more detail, and it will be great if you can point me to the Park paper when available. Cheers!

**Comment by alisonrgray** [comment]
Hi @wenegrat (and @dhruvbalwada),
The Park et al 2021 paper is now on arxiv [here](https://arxiv.org/abs/2105.09707).  It deals explicitly with the mean field estimation (unlike Kuusela and Stein 2018).  Happy to chat more about what you're working on, if you are still interested.  Hope you are doing well!

**Comment by wenegrat** [comment]
Hey thanks! Great timing, as I was literally just thinking about bugging
@dhruvbalwada about this yesterday.

I'll take a look, and let you know if I have any more questions. Hope you
are doing well also!
